Repository cessda/cessda.cvs.two, pull requests merged in 2023-06, with the labels that each got.

#601 Update Node.JS to 16.20.0, update NPM to 8.19.4
  package-lock.json
  package.json
  pom.xml
  src/main/webapp/app/editor/editor-detail.component.ts
  src/main/webapp/app/shared/util/vocabulary-util.ts
  src/main/webapp/app/shared/vocabulary-search-result/vocabulary-search-result.component.ts
Labels: dependencies, javascript

#684 Feature/455
  src/main/java/eu/cessda/cvs/service/dto/CodeDTO.java
  src/main/java/eu/cessda/cvs/service/impl/VocabularyServiceImpl.java
  src/main/resources/templates/xml/export-ddi_rdf.xml
  src/main/webapp/app/agency/agency-update.component.html
Labels: resolved

#704 Fix presence of NUL characters/empty bytes in various export types (SKOS, PDF, HTML)
  src/main/java/eu/cessda/cvs/web/rest/EditorResource.java
  src/main/java/eu/cessda/cvs/web/rest/VocabularyResourceV2.java
  src/main/java/eu/cessda/cvs/web/rest/utils/AccessibleByteArrayOutputStream.java
Labels: bug, major
